name: Code Standards & Quality

on:
  workflow_call:
    inputs:
      node-version:
        type: string
        default: "20"
      run-build:
        type: boolean
        default: false

jobs:
  code-standards: # Diubah dari "build" untuk menghindari konflik nama
    name: Check Code standards & Quality
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - name: 🛫 Checkout code
        uses: actions/checkout@v4

      - name: "📦 Install pnpm"
        uses: pnpm/action-setup@v2
        with:
          version: "8.10.0" # Diperbaiki dari "8.10.o" ke "8.10.0"

      - name: 🔧 Setup Node.js ${{ inputs.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: "pnpm"

      - name: 📦 Install dependencies
        run: pnpm install --frozen-lockfile

      - name: 🔎 Lint code
        run: pnpm run lint

      - name: 📝 Checking code format
        run: pnpm run format:check

      - name: 💪 Type Checking
        run: pnpm dlx astro check

      - name: 🚀 Build the project
        if: ${{ inputs.run-build }}
        run: pnpm run build
