on:
  push:
    branches:
      - main

name: Minimal Workflow

permissions:
  contents: write

jobs:
  placeholder-job:
    runs-on: ubuntu-latest
    steps:
      - name: Placeholder Step
        run: echo "This is a minimal workflow to avoid errors."
